// Explicit usings: the console project has ImplicitUsings enabled in its .csproj;
// Unity's own compilation of Assembly-CSharp does not respect that setting, so this
// Unity copy needs them stated even though the master copy at game/src/ doesn't.
//
// GENERATED by game/scripts/sync-unity.mjs — edit game/src/Eyeland.Duel/ instead.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Eyeland.Duel;

// ─────────────────────────────────────────────────────────────────────────────
// Cards as data.
//
// A card in game/data/cards.json names effects from the registry below plus
// their parameters. Adding a CARD needs no C# and no recompile. Only a
// genuinely new kind of EFFECT does. That split is Spellsource's (see
// game/research/FIELD-NOTES-card-engines.md); the eleven cards in the pool
// today need exactly five effects between them.
//
// Parsing failures throw with the offending card id rather than silently
// producing a broken card, per DESIGN.md principle 3: never lie to the player
// about fairness. A card that quietly did nothing would be exactly that lie.
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>One step of a card's play effect: an effect name plus its parameters.</summary>
public sealed record EffectStep(
    string Effect,
    int Amount = 0,
    int Attack = 0,
    int Health = 0,
    string? Card = null,
    string? Condition = null);

/// <summary>A deck recipe: how many copies of each card, in a stable order.</summary>
public sealed record DeckRecipe(IReadOnlyList<string> Order, IReadOnlyDictionary<string, int> Counts);

/// <summary>The whole parsed card file.</summary>
public sealed record CardData(IReadOnlyList<CardDef> Cards, DeckRecipe StarterDeck)
{
    public CardDef ById(string id) =>
        Cards.FirstOrDefault(c => c.Id == id)
        ?? throw new KeyNotFoundException($"No card with id '{id}'.");
}

public static class CardLoader
{
    /// <summary>
    /// Effects a card may name. Adding a card never touches this; adding a new KIND
    /// of effect does. Each takes the resolution context and its parsed step.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, Action<DuelContext, EffectStep>> Effects =
        new Dictionary<string, Action<DuelContext, EffectStep>>(StringComparer.OrdinalIgnoreCase)
        {
            ["damage"] = (ctx, s) => Duel.Effects.Damage(ctx, s.Amount),
            ["damageEnemyCaster"] = (ctx, s) =>
            {
                ctx.Opponent.Health -= s.Amount;
                ctx.Log.Add($"{ctx.Opponent.Name} takes {s.Amount} damage.");
            },
            ["damageAllEnemyCreatures"] = (ctx, s) => Duel.Effects.DamageAllEnemyCreatures(ctx, s.Amount),
            ["healCaster"] = (ctx, s) => Duel.Effects.Heal(ctx, ctx.Owner, s.Amount),
            ["draw"] = (ctx, s) => Duel.Effects.Draw(ctx, ctx.Owner, s.Amount),

            // ── class verbs ───────────────────────────────────────────────────
            ["buffTarget"] = (ctx, s) =>
            {
                if (ctx.Target is { } t) Duel.Effects.Buff(ctx, t, s.Card ?? "Buff", s.Attack, s.Health);
            },
            ["buffSelf"] = (ctx, s) =>
            {
                var last = ctx.Owner.Board.LastOrDefault(c => c.IsAlive);
                if (last is not null) Duel.Effects.Buff(ctx, last, s.Card ?? "Buff", s.Attack, s.Health);
            },
            ["buffAllFriendly"] = (ctx, s) =>
                Duel.Effects.BuffAllFriendly(ctx, s.Card ?? "Inspired", s.Attack, s.Health),
            ["grantTaunt"] = (ctx, s) =>
            {
                if (ctx.Target is { } t) Duel.Effects.GrantTaunt(ctx, t);
            },
            ["healTarget"] = (ctx, s) =>
            {
                if (ctx.Target is { } t) Duel.Effects.HealCreature(ctx, t, s.Amount);
            },
            ["damageOwnCaster"] = (ctx, s) => Duel.Effects.DamageOwnCaster(ctx, s.Amount),
            ["damageRandomEnemyCreature"] = (ctx, s) => Duel.Effects.DamageRandomEnemyCreature(ctx, s.Amount),
            ["destroyTarget"] = (ctx, s) =>
            {
                if (ctx.Target is { } t) Duel.Effects.DestroyCreature(ctx, t);
            },
            ["freezeTarget"] = (ctx, s) =>
            {
                if (ctx.Target is { } t) Duel.Effects.Freeze(ctx, t);
            },
            ["summon"] = (ctx, s) =>
            {
                if (s.Card is { } id) Duel.Effects.Summon(ctx, id, Math.Max(1, s.Amount));
            },
        };

    /// <summary>Conditions a step may be gated on.</summary>
    public static readonly IReadOnlyDictionary<string, Func<DuelContext, bool>> Conditions =
        new Dictionary<string, Func<DuelContext, bool>>(StringComparer.OrdinalIgnoreCase)
        {
            ["firstSpellThisTurn"] = ctx => ctx.IsFirstSpellThisTurn,
        };

    public static CardData FromJson(string json)
    {
        var root = JsonValue.Parse(json);

        var cards = new List<CardDef>();

        // Cards may sit at the root (the original single-pool shape) or be grouped into
        // named sets. Both are supported so the file can be split per class later without
        // another loader change.
        foreach (var node in root["cards"].Array)
            cards.Add(ReadCard(node));

        foreach (var set in root["sets"].Array)
            foreach (var node in set["cards"].Array)
                cards.Add(ReadCard(node));

        var duplicates = cards.GroupBy(c => c.Id).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        if (duplicates.Count > 0)
            throw new FormatException($"Duplicate card ids: {string.Join(", ", duplicates)}.");

        var deckNode = root["starterDeck"];
        var order = deckNode["order"].Array.Select(v => v.AsString()).ToList();
        var counts = new Dictionary<string, int>();
        foreach (var id in order)
            counts[id] = deckNode["counts"][id].AsInt(1);

        return new CardData(cards, new DeckRecipe(order, counts));
    }

    private static CardDef ReadCard(JsonValue n)
    {
        var id = n["id"].AsString();
        if (id.Length == 0) throw new FormatException("A card is missing its 'id'.");

        try
        {
            var steps = n["onPlay"].Array.Select(ReadStep).ToList();

            return new CardDef(
                Id: id,
                Name: n["name"].AsString(id),
                Cost: n["cost"].AsInt(),
                Type: Enum<CardType>(n["type"].AsString("creature"), id, "type"),
                Element: Enum<Element>(n["element"].AsString("fire"), id, "element"),
                Rarity: Enum<Rarity>(n["rarity"].AsString("common"), id, "rarity"),
                Text: n["text"].AsString(),
                Class: Enum<PlayerClass>(n["class"].AsString("neutral"), id, "class"),
                Attack: n["attack"].AsInt(),
                Health: n["health"].AsInt(),
                Taunt: n["taunt"].AsBool(),
                Keywords: ReadKeywords(n["keywords"], id),
                SpellDamage: n["spellDamage"].AsInt(),
                OnDeath: ReadSteps(n["deathrattle"], id),
                Targeting: Enum<TargetRule>(n["targeting"].AsString("none"), id, "targeting"),
                OnPlay: steps.Count == 0 ? null : Compile(steps),
                Aura: n.Has("aura") ? ReadAura(n["aura"], id) : null);
        }
        catch (Exception ex) when (ex is not FormatException)
        {
            throw new FormatException($"Card '{id}' failed to load: {ex.Message}", ex);
        }
    }

    /// <summary>Compiles an effect-step array into a delegate, or null when empty.</summary>
    private static CardEffect? ReadSteps(JsonValue node, string cardId)
    {
        var steps = node.Array.Select(ReadStep).ToList();
        return steps.Count == 0 ? null : Compile(steps);
    }

    private static IReadOnlyList<Stat>? ReadKeywords(JsonValue node, string cardId)
    {
        var raw = node.Array.Select(v => v.AsString()).Where(v => v.Length > 0).ToList();
        if (raw.Count == 0) return null;

        var keywords = raw.Select(k => Enum<Stat>(k, cardId, "keywords")).ToList();
        foreach (var k in keywords)
            if (k is Stat.Attack or Stat.MaxHealth)
                throw new FormatException($"Card '{cardId}' lists '{k}' as a keyword; it is a stat.");
        return keywords;
    }

    private static EffectStep ReadStep(JsonValue n)
    {
        var effect = n["effect"].AsString();
        if (!Effects.ContainsKey(effect))
            throw new FormatException(
                $"Unknown effect '{effect}'. Known: {string.Join(", ", Effects.Keys)}.");

        var condition = n.Has("condition") ? n["condition"].AsString() : null;
        if (condition is not null && !Conditions.ContainsKey(condition))
            throw new FormatException(
                $"Unknown condition '{condition}'. Known: {string.Join(", ", Conditions.Keys)}.");

        return new EffectStep(
            effect,
            n["amount"].AsInt(),
            n["attack"].AsInt(),
            n["health"].AsInt(),
            n.Has("card") ? n["card"].AsString() : null,
            condition);
    }

    /// <summary>Turns the parsed steps into the single delegate CardDef expects.</summary>
    private static CardEffect Compile(IReadOnlyList<EffectStep> steps) => ctx =>
    {
        foreach (var step in steps)
        {
            if (step.Condition is { } c && !Conditions[c](ctx)) continue;
            Effects[step.Effect](ctx, step);
        }
    };

    private static AuraDef ReadAura(JsonValue n, string cardId)
    {
        var scope = Enum<AuraScope>(n["scope"].AsString("friendlyOthers"), cardId, "aura.scope");
        var mods = n["mods"].Array
            .Select(m => new StatMod(Enum<Stat>(m["stat"].AsString(), cardId, "aura.mods.stat"), m["amount"].AsInt()))
            .ToList();

        if (mods.Count == 0)
            throw new FormatException($"Card '{cardId}' declares an aura with no mods.");

        return new AuraDef(scope, mods, n["text"].AsString());
    }

    private static T Enum<T>(string raw, string cardId, string field) where T : struct
    {
        if (System.Enum.TryParse<T>(raw, ignoreCase: true, out var parsed))
            return parsed;
        throw new FormatException(
            $"Card '{cardId}' has an invalid {field} '{raw}'. Valid: " +
            string.Join(", ", System.Enum.GetNames(typeof(T))) + ".");
    }
}
