// Explicit usings: the console project has ImplicitUsings enabled in its .csproj;
// Unity's own compilation of Assembly-CSharp does not respect that setting, so this
// Unity copy needs them stated even though the master copy at game/src/ doesn't.
//
// GENERATED by game/scripts/sync-unity.mjs — edit game/src/Eyeland.Duel/ instead.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Eyeland.Duel;

public enum Element { Fire, Water, Storm }

public enum CardType { Spell, Creature }

public enum Rarity { Common, Rare, Legendary }

/// <summary>
/// A card's class. Neutral cards go in any deck; the rest are class-locked.
///
/// The twelve names are the SRD 5.1 classes, used under CC-BY-4.0 (see
/// game/data/cards.json's legal block). Tinkerer is Adam's own addition from the
/// Milanote export, deliberately not an SRD class.
/// </summary>
public enum PlayerClass
{
    Neutral,
    Barbarian, Bard, Cleric, Druid, Fighter, Monk,
    Paladin, Ranger, Rogue, Sorcerer, Warlock, Wizard,
    Tinkerer,
}

/// <summary>
/// The result of resolving a card: what happened, for the log and the console UI.
/// Effects append here instead of printing directly, so the engine stays UI-agnostic
/// (the same CardDef will later run unmodified inside the Unity duel scene).
/// </summary>
public sealed class ResolutionLog
{
    public List<string> Lines { get; } = new();
    public void Add(string line) => Lines.Add(line);
}

/// <summary>
/// Everything needed to resolve a card is passed through one context object,
/// rather than threading Owner/Opponent/Target through every effect signature.
/// </summary>
public sealed class DuelContext
{
    public required DuelState State { get; init; }
    public required Caster Owner { get; init; }
    public required Caster Opponent { get; init; }
    public BoardCreature? Target { get; init; }
    public bool IsFirstSpellThisTurn { get; init; }
    public required ResolutionLog Log { get; init; }

    /// <summary>
    /// Whether Spell Damage applies to damage from this resolution. True only for spell
    /// CARDS. Hearthstone's rule, and the one worth copying: Spell Damage boosts spells,
    /// never hero powers and never battlecries. Without this a Wizard's 1-damage hero
    /// power silently became 2 next to an apprentice.
    /// </summary>
    public bool SpellDamageApplies { get; init; }
}

public delegate void CardEffect(DuelContext ctx);

/// <summary>
/// Whether a card's effect can/must be aimed at a specific enemy creature.
/// OptionalCreature covers cards like "deal 3 damage" (Effects.Damage falls back to face
/// when Target is null); RequiredCreature covers cards restricted to "...to a creature".
/// </summary>
public enum TargetRule { None, OptionalCreature, RequiredCreature }

/// <summary>
/// An immutable card definition — the "printed card." Playing a copy never mutates
/// this; creatures get their own BoardCreature instance with independent Attack/Health.
/// </summary>
public sealed record CardDef(
    string Id,
    string Name,
    int Cost,
    CardType Type,
    Element Element,
    Rarity Rarity,
    string Text,
    PlayerClass Class = PlayerClass.Neutral,
    int Attack = 0,
    int Health = 0,
    bool Taunt = false,
    TargetRule Targeting = TargetRule.None,
    CardEffect? OnPlay = null,
    AuraDef? Aura = null,
    IReadOnlyList<Stat>? Keywords = null,
    int SpellDamage = 0,
    CardEffect? OnDeath = null)
{
    /// <summary>Whether this card is printed with a keyword. Taunt stays a top-level flag for compatibility.</summary>
    public bool Has(Stat keyword) =>
        (keyword == Stat.Taunt && Taunt) || (Keywords?.Contains(keyword) ?? false);

    public override string ToString() =>
        Type == CardType.Creature
            ? $"{Name} ({Cost}) [{Attack}/{Health}]"
            : $"{Name} ({Cost})";
}

public static class Effects
{
    /// <summary>Total Spell Damage the owner's board is contributing.</summary>
    public static int SpellPower(DuelContext ctx) =>
        ctx.SpellDamageApplies ? ctx.Owner.Board.Where(c => c.IsAlive).Sum(c => c.SpellDamage) : 0;

    /// <summary>
    /// Damages the chosen target, or the opponent's face if no target was chosen.
    /// Spell Damage is added here, so it applies to spell effects and not to combat.
    /// </summary>
    public static void Damage(DuelContext ctx, int amount)
    {
        amount += SpellPower(ctx);
        if (ctx.Target is { } creature)
        {
            creature.TakeDamage(amount);
            ctx.Log.Add($"{creature.Source.Name} takes {amount} damage ({Math.Max(creature.Health, 0)} health left).");
        }
        else
        {
            ctx.Opponent.Health -= amount;
            ctx.Log.Add($"{ctx.Opponent.Name} takes {amount} damage ({Math.Max(ctx.Opponent.Health, 0)} health left).");
        }
    }

    public static void DamageAllEnemyCreatures(DuelContext ctx, int amount)
    {
        amount += SpellPower(ctx);
        foreach (var creature in ctx.Opponent.Board.ToList())
        {
            creature.TakeDamage(amount);
            ctx.Log.Add($"{creature.Source.Name} takes {amount} damage ({Math.Max(creature.Health, 0)} health left).");
        }
    }

    public static void Heal(DuelContext ctx, Caster who, int amount)
    {
        who.Health = Math.Min(who.Health + amount, who.MaxHealth);
        ctx.Log.Add($"{who.Name} restores {amount} health ({who.Health} health now).");
    }

    public static void Draw(DuelContext ctx, Caster who, int count = 1)
    {
        for (var i = 0; i < count; i++)
            who.DrawCard(ctx.Log);
    }

    /// <summary>Permanently buffs one creature. Layer 1 of the stat onion.</summary>
    public static void Buff(DuelContext ctx, BoardCreature target, string name, int attack, int health)
    {
        var mods = new List<StatMod>();
        if (attack != 0) mods.Add(new StatMod(Stat.Attack, attack));
        if (health != 0) mods.Add(new StatMod(Stat.MaxHealth, health));
        if (mods.Count == 0) return;

        target.AddEnchantment(new Enchantment(name, mods));
        ctx.Log.Add($"{target.Source.Name} gains {(attack != 0 ? $"+{attack} Attack" : "")}" +
                    $"{(attack != 0 && health != 0 ? " and " : "")}" +
                    $"{(health != 0 ? $"+{health} Health" : "")}.");
    }

    public static void BuffAllFriendly(DuelContext ctx, string name, int attack, int health)
    {
        foreach (var c in ctx.Owner.Board.Where(c => c.IsAlive).ToList())
            Buff(ctx, c, name, attack, health);
    }

    public static void GrantTaunt(DuelContext ctx, BoardCreature target)
    {
        target.AddEnchantment(Enchantment.Of("Taunt", new StatMod(Stat.Taunt, 1)));
        ctx.Log.Add($"{target.Source.Name} gains Taunt.");
    }

    /// <summary>Restores health to a creature by removing damage. Never exceeds MaxHealth.</summary>
    public static void HealCreature(DuelContext ctx, BoardCreature target, int amount)
    {
        var healed = target.Restore(amount);
        ctx.Log.Add(healed > 0
            ? $"{target.Source.Name} restores {healed} health."
            : $"{target.Source.Name} is already undamaged.");
    }

    /// <summary>The Warlock tax: pay your own health for effect.</summary>
    public static void DamageOwnCaster(DuelContext ctx, int amount)
    {
        ctx.Owner.Health -= amount;
        ctx.Log.Add($"{ctx.Owner.Name} pays {amount} health.");
    }

    /// <summary>Sorcerer volatility: hits something on the enemy board, chosen at random.</summary>
    public static void DamageRandomEnemyCreature(DuelContext ctx, int amount)
    {
        var living = ctx.Opponent.Board.Where(c => c.IsAlive).ToList();
        if (living.Count == 0)
        {
            ctx.Opponent.Health -= amount;
            ctx.Log.Add($"Nothing to strike — {ctx.Opponent.Name} takes {amount}.");
            return;
        }
        var pick = living[ctx.State.Random.Next(living.Count)];
        pick.TakeDamage(amount);
        ctx.Log.Add($"{pick.Source.Name} is struck for {amount}.");
    }

    /// <summary>Destroy ignores Divine Shield — a shield absorbs damage, not annihilation.</summary>
    public static void DestroyCreature(DuelContext ctx, BoardCreature target)
    {
        target.Destroy();
        ctx.Log.Add($"{target.Source.Name} is destroyed.");
    }

    public static void Freeze(DuelContext ctx, BoardCreature target)
    {
        target.Frozen = true;
        ctx.Log.Add($"{target.Source.Name} is frozen.");
    }

    /// <summary>Summons copies of a card by id, respecting the 7-creature board cap.</summary>
    public static void Summon(DuelContext ctx, string cardId, int count)
    {
        var card = CardSet.ById(cardId);
        for (var i = 0; i < count; i++)
        {
            if (ctx.Owner.Board.Count >= 7)
            {
                ctx.Log.Add("The board is full.");
                return;
            }
            ctx.Owner.Board.Add(BoardCreature.FromCard(card));
            ctx.Log.Add($"{card.Name} is summoned.");
        }
    }
}

/// <summary>
/// The card pool, loaded from <c>game/data/cards.json</c> at first use.
///
/// The named properties below are conveniences for code that wants a specific card
/// (tests, the console harness, the Unity scenes). They resolve by id out of the
/// loaded data, so adding a card to the JSON needs no change here at all — only a
/// card that code refers to by name needs a property.
///
/// Ember Bolt, Tidewisp, and Eye of the Storm are the three showcase cards from the
/// eyeland.cards landing page: this is the same game, not a separate prototype. The
/// rest fill out the curve around the same three-element identity: Fire = tempo/burn,
/// Water = control/sustain, Storm = card draw/AoE.
/// </summary>
public static class CardSet
{
    private static CardData? _data;

    /// <summary>The parsed card file. Loaded once, on first access.</summary>
    public static CardData Data => _data ??= CardLoader.FromJson(CardSource.Json);

    /// <summary>
    /// Replaces the loaded pool. For tests and for any future card editor that wants to
    /// preview edited data without restarting. Pass null to fall back to the shipped file.
    /// </summary>
    public static void Load(string? json)
    {
        _data = json is null ? null : CardLoader.FromJson(json);
    }

    public static CardDef ById(string id) => Data.ById(id);

    public static CardDef EmberBolt => ById("ember-bolt");
    public static CardDef Tidewisp => ById("tidewisp");
    public static CardDef EyeOfTheStorm => ById("eye-of-the-storm");
    public static CardDef GlowingEmber => ById("glowing-ember");
    public static CardDef CinderWolf => ById("cinder-wolf");
    public static CardDef TideGuard => ById("tide-guard");
    public static CardDef Riptide => ById("riptide");
    public static CardDef SquallCaller => ById("squall-caller");
    public static CardDef StormcallerElemental => ById("stormcaller-elemental");
    public static CardDef RollingThunder => ById("rolling-thunder");
    public static CardDef StormTotem => ById("storm-totem");

    public static IReadOnlyList<CardDef> All => Data.Cards;

    /// <summary>The hero power for a class, falling back to neutral.</summary>
    public static HeroPower PowerFor(PlayerClass cls) => Data.PowerFor(cls);

    /// <summary>
    /// The symmetric v0 starter deck, built from the recipe in the card file: 2 copies of
    /// each common staple, 1 of each rare, 1 legendary. 16 cards — enough to prove the duel
    /// loop is fun without building the full 40-card economy v1 (Deck) owns.
    /// </summary>
    public static List<CardDef> StarterDeck()
    {
        var recipe = Data.StarterDeck;
        var deck = new List<CardDef>();
        foreach (var id in recipe.Order)
        {
            var card = Data.ById(id);
            var copies = recipe.Counts.TryGetValue(id, out var n) ? n : 1;
            for (var i = 0; i < copies; i++) deck.Add(card);
        }
        return deck;
    }
}
