// Explicit usings: the console project has ImplicitUsings enabled in its .csproj;
// Unity's own compilation of Assembly-CSharp does not respect that setting, so this
// Unity copy needs them stated even though the master copy at game/src/ doesn't.
//
// GENERATED by game/scripts/sync-unity.mjs — edit game/src/Eyeland.Duel/ instead.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Eyeland.Duel;

/// <summary>
/// A dumb-but-legal opponent for v0: play the most expensive affordable card each step
/// (aiming damage at the strongest enemy creature when a target is useful), then attack
/// with everything that can attack, respecting taunt. Enough to prove the duel loop is
/// fun to play against — balance-quality AI is a later problem.
/// </summary>
public sealed class GreedyAI : IPlayerController
{
    public string Name { get; }

    public GreedyAI(string name) => Name = name;

    public PlayerAction ChooseAction(DuelState state, Caster me, Caster opponent)
    {
        var playable = me.Hand.Where(c => c.Cost <= me.Pips).OrderByDescending(c => c.Cost).ToList();
        if (playable.Count > 0)
        {
            var card = playable[0];
            BoardCreature? target = card.Targeting switch
            {
                TargetRule.None => null,
                _ => opponent.Board.Where(c => c.IsAlive).OrderByDescending(c => c.Attack).FirstOrDefault(),
            };
            if (card.Targeting == TargetRule.RequiredCreature && target is null)
            {
                // No legal creature to hit — this card is unplayable right now, skip it.
                playable.RemoveAt(0);
            }
            else
            {
                return new PlayCard(card, target);
            }
        }

        // Hero power before passing: unspent mana is wasted mana. Deliberately AFTER
        // cards, since a card is almost always better value than 2 mana of hero power.
        var power = CardSet.PowerFor(me.Class);
        if (!me.HeroPowerUsedThisTurn && me.Pips >= power.Cost)
        {
            var needsTarget = power.Targeting == TargetRule.RequiredCreature;
            var pick = opponent.Board.FirstOrDefault(c => c.IsAlive && !c.Stealth);
            if (!needsTarget || pick is not null)
                return new UseHeroPower(needsTarget ? pick : null);
        }

        // Ask the engine what is legal rather than re-deriving Taunt/Rush/Stealth here.
        // Proposing an attack the engine then refuses would spin this loop forever.
        foreach (var candidate in me.Board.Where(c => c.CanAttackNow))
        {
            var targets = TurnEngine.LegalAttackTargets(state, candidate);
            if (targets.Count == 0) continue;

            // Prefer a kill it survives, then face, then anything legal.
            var best = targets.FirstOrDefault(t => t is not null && t.Health <= candidate.Attack && t.Attack < candidate.Health)
                       ?? (targets.Contains(null) ? null : targets[0]);
            return new AttackAction(candidate, best);
        }

        return new PassTurn();
    }
}
