// Explicit usings: the console project has ImplicitUsings enabled in its .csproj;
// Unity's own compilation of Assembly-CSharp does not respect that setting, so this
// Unity copy needs them stated even though the master copy at game/src/ doesn't.
//
// GENERATED by game/scripts/sync-unity.mjs — edit game/src/Eyeland.Duel/ instead.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Eyeland.Duel;

/// <summary>Small deterministic expedition. Rewards are derived from cleared encounters,
/// so replaying a result or loading a save cannot duplicate inventory.</summary>
public sealed class IslandRun
{
    public const int DeckSize = 12;
    public int Seed { get; }
    public int Cleared { get; private set; }
    public List<string> DeckIds { get; private set; }
    public int Resources => Cleared * (Cleared + 1);
    public bool Complete => Cleared == 4;
    public static readonly string[] Creatures = { "cinder-wolf", "tidewisp", "galehart", "ember-reach-warden" };
    public static readonly string[] Places = { "Ashwood camp", "Moonpool camp", "Stormgrass camp", "Warden's summit" };
    private static readonly string[] Starter = { "ember-bolt", "glowing-ember", "tide-guard", "squall-caller", "stormcaller-elemental", "riptide" };
    public IslandRun(int seed, int cleared = 0, IEnumerable<string>? deck = null)
    {
        if (cleared < 0 || cleared > 4) throw new ArgumentException("Invalid cleared encounter count.");
        Seed = seed; Cleared = cleared;
        DeckIds = Starter.SelectMany(id => new[] { id, id }).ToList();
        if (deck != null) SetDeck(deck);
    }
    public Dictionary<string, int> Owned()
    {
        var owned = Starter.ToDictionary(id => id, _ => 2);
        for (var i = 0; i < Cleared; i++) owned[Creatures[i]] = i == 3 ? 1 : 2;
        return owned;
    }
    public void SetDeck(IEnumerable<string> ids)
    {
        var list = ids.ToList(); var owned = Owned();
        if (list.Count != DeckSize || list.Any(id => id == null || !owned.ContainsKey(id)) ||
            list.GroupBy(id => id).Any(g => g.Count() > owned[g.Key]))
            throw new ArgumentException("Choose exactly 12 cards from your collection.");
        DeckIds = list;
    }
    public List<CardDef> Deck() => DeckIds.OrderBy(id => id, StringComparer.Ordinal).Select(id => CardSet.All.Single(c => c.Id == id)).ToList();
    public CardDef Creature(int index) => CardSet.All.Single(c => c.Id == Creatures[index]);
    public int EnemyHealth(int index) => 14 + index * 5;
    public List<CardDef> EnemyDeck(int index)
    {
        if (index < 0 || index > 3) throw new ArgumentOutOfRangeException(nameof(index));
        var ids = new List<string>();
        // Seed varies the supporting element while preserving the authored difficulty arc.
        var support = new Random(unchecked(Seed + index * 7919)).Next(2) == 0 ? "tide-guard" : "squall-caller";
        foreach (var id in new[] { "glowing-ember", support, Creatures[index], "ember-bolt", "stormcaller-elemental", "riptide" })
            ids.AddRange(new[] { id, id });
        return ids.Select(id => CardSet.All.Single(c => c.Id == id)).ToList();
    }
    public bool RecordVictory(int index)
    {
        if (Complete || index != Cleared) return false;
        Cleared++; return true;
    }
}
