#!/usr/bin/env node
// Copies the portable duel core into the Unity project.
//
// game/README.md's rule: edit game/src/ first, then re-copy, never edit the Unity
// copy. This does the copy, so the two cannot drift by hand.
//
// Two real differences the Unity copy needs, both applied here:
//   1. Explicit usings. The .csproj has ImplicitUsings enabled; Unity's compilation
//      of Assembly-CSharp does not respect that setting.
//   2. cards.json lands in Assets/Resources so a TextAsset can load it. Unity has no
//      access to the repo layout or to embedded resources at runtime.
//
// Usage: node game/scripts/sync-unity.mjs [--check]
//        --check exits non-zero if anything is out of date, for CI.

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const SRC = join(REPO, "game", "src", "Eyeland.Duel");
const DEST = join(REPO, "game", "unity", "Assets", "Scripts", "Duel");
const DATA = join(REPO, "game", "data", "cards.json");
const RES = join(REPO, "game", "unity", "Assets", "Resources");

const HEADER = `// Explicit usings: the console project has ImplicitUsings enabled in its .csproj;
// Unity's own compilation of Assembly-CSharp does not respect that setting, so this
// Unity copy needs them stated even though the master copy at game/src/ doesn't.
//
// GENERATED by game/scripts/sync-unity.mjs — edit game/src/Eyeland.Duel/ instead.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

`;

// Files that only make sense outside Unity. RequiredMemberPolyfill is Unity-only and
// lives solely in the Unity folder, so it is never overwritten from src.
const SKIP = new Set([]);

const checkOnly = process.argv.includes("--check");
let stale = 0;

function put(path, contents, label) {
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === contents) return;
  stale++;
  if (checkOnly) {
    console.log(`STALE  ${label}`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
  console.log(`synced ${label}`);
}

for (const file of readdirSync(SRC).filter((f) => f.endsWith(".cs"))) {
  if (SKIP.has(file)) continue;
  const body = readFileSync(join(SRC, file), "utf8");
  put(join(DEST, file), HEADER + body, `Duel/${file}`);
}

put(join(RES, "cards.json"), readFileSync(DATA, "utf8"), "Resources/cards.json");

if (checkOnly && stale > 0) {
  console.error(`\n${stale} file(s) out of date. Run: node game/scripts/sync-unity.mjs`);
  process.exit(1);
}
console.log(stale === 0 ? "Unity copy already up to date." : `\nSynced ${stale} file(s).`);
